name: "Bug: Playback"
description: Report a video/audio playback issue
title: "[Playback] "
labels: ["bug", "playback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out as much as you can, playback issues are very environment + media dependent.

  - type: input
    id: app_version
    attributes:
      label: Moonfin version
      description: The app version / release tag (e.g., v2.0.0)
      placeholder: v2.0.0
    validations:
      required: true

  - type: input
    id: webos_version
    attributes:
      label: webOS version
      description: "Example: webOS 23 / 8.x / 7.x (whatever your TV reports)"
      placeholder: webOS 4
    validations:
      required: true

  - type: input
    id: tv_model
    attributes:
      label: TV model
      description: "Example: OLED55C1PUA"
      placeholder: 
    validations:
      required: false

  - type: input
    id: jellyfin_version
    attributes:
      label: Jellyfin server version
      placeholder: 10.x.x
    validations:
      required: true

  - type: dropdown
    id: item_type
    attributes:
      label: Content type
      options:
        - Movie
        - Episode
        - Live TV
        - Other
    validations:
      required: true

  - type: textarea
    id: media_info
    attributes:
      label: Media details (as much as you know, check the info bottom at the bottom right of the player)
      description: Container, resolution, HDR type, video codec/profile, audio codec/channels, subtitle type, bitrate
      placeholder: |
        Container: MKV
        Resolution: 3840x2160
        HDR: HDR10
        Video: HEVC Main10@L5.1
        Audio: EAC3 5.1
        Subs: PGS (enabled)
        Bitrate: ~25 Mbps
    validations:
      required: true

  - type: dropdown
    id: playback_path
    attributes:
      label: Playback path
      options:
        - Direct Play
        - Transcode
        - Not sure
    validations:
      required: true

  - type: checkboxes
    id: symptoms
    attributes:
      label: Symptoms (check all that apply)
      options:
        - label: Black screen / endless spinner
        - label: Audio only (no video)
        - label: Stuttering / frame drops
        - label: A/V sync issues
        - label: Seeking/scrubbing broken
        - label: Subtitles missing or incorrect
        - label: Unexpected forced transcode
        - label: App crashes / exits

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open ...
        2. Select ...
        3. Press Play ...
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      options:
        - Always
        - Sometimes
        - Once
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / errors (optional)
      description: Paste any on-screen errors, inspector console output, or attach photos/screenshots.
    validations:
      required: false
